all: tests bellman_ford bfs kruskal
tests: tests.cpp utils.h
	g++ -Wall --std=c++0x -o tests tests.cpp utils.h
bellman_ford: bellman_ford.cpp utils.h
	g++ -Wall --std=c++0x -o bellman_ford bellman_ford.cpp utils.h
bfs: bfs.cpp utils.h
	g++ -Wall --std=c++0x -o bfs bfs.cpp utils.h
kruskal: kruskal.cpp utils.h
	g++ -Wall --std=c++0x -o kruskal kruskal.cpp utils.h
prim: prim.cpp utils.h
	g++ -Wall --std=c++0x -o prim prim.cpp utils.h
