all: bubblesort insertion_sort selection_sort
bubblesort: utils.h bubblesort.c
	gcc --std=c99 -o bubblesort utils.h bubblesort.c
insertion_sort: utils.h insertion_sort.c
	gcc --std=c99 -o insertion_sort utils.h insertion_sort.c
selection_sort: utils.h selection_sort.c
	gcc --std=c99 -o selection_sort utils.h selection_sort.c
