all: bubble_sort insertion_sort selection_sort
bubblesort: utils.h bubble_sort.c
	gcc --std=c99 -o bubble_sort utils.h bubble_sort.c
insertion_sort: utils.h insertion_sort.c
	gcc --std=c99 -o insertion_sort utils.h insertion_sort.c
selection_sort: utils.h selection_sort.c
	gcc --std=c99 -o selection_sort utils.h selection_sort.c
